# tried using the below code but throwing copy error
services:
  client:
    build: ./client
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - ai-fasion-mirror

  server:
    build: ./server
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - ai-fasion-mirror

networks:
  ai-fasion-mirror:

# tried defining the volume instead of network
# services:
#   client:
#     build: ./client/.
#     ports:
#       - 127.0.0.1:3000:3000
#     volumes:
#       - ./:./

# tried defining build instruction from compose file
  # client:
  #   build: ./client/.
  #   image: node:20.16.0-alpine
  #   command: npm ci && npm run dev
  #   ports:
  #     - 127.0.0.1:3000:3000
  #   working_dir: /app

  # server:
  #   build: ./server/.
  #   environment:
  #     SERVER_PORT: 8080
  #     PREAPI_URL: "https://pre.cm/scribe.php"
  #     CLIENT_BASE_URL: http://localhost:3000
  #     SERVER_BASE_URL: http://localhost:8080
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 127.0.0.1:8080:8080
