services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
    networks:
      - ai-fasion-mirror

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    # devices:
    #   - /dev/video0:/dev/video0
    env_file:
      - .env
    networks:
      - ai-fasion-mirror

  docs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    ports:
      - 127.0.0.1:4000:4000

networks:
  ai-fasion-mirror: