services:
  client:
    # image: node:20.16.0-alpine
    # command: sh -c "npm i && npm run dev"
    # ports:
    #   - 127.0.0.1:3000:3000
    # environment:
    #   SERVER_PORT: 8080
    #   PREAPI_URL: "https://pre.cm/scribe.php"
    #   CLIENT_BASE_URL: http://localhost:3000
    #   SERVER_BASE_URL: http://localhost:8080
    # working_dir: /app/client
    # volumes:
    #   - ./:/app
    build: ./client
    ports:
      - 127.0.0.1:3000:3000

  server:
    # image: node:20.16.0-alpine
    # command: sh -c "npm i && npm run dev"
    # ports:
    #   - 127.0.0.1:8080:8080
    # environment:
    #   SERVER_PORT: 8080
    #   PREAPI_URL: "https://pre.cm/scribe.php"
    #   CLIENT_BASE_URL: http://localhost:3000
    #   SERVER_BASE_URL: http://localhost:8080
    # working_dir: /app/server
    # volumes:
    #   - ./:/app
    build: ./server
    ports:
      - 127.0.0.1:8080:8080