services:
  # note: does not hot reload T_T
  client-local:
    build:
      context: .
      dockerfile: ./client/Dockerfile.local
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./client/pages:/app/pages
      - ./client/components:/app/components
      - ./client/services:/app/services
      - ./client/utils:/app/utils
      - ./client/styles:/app/styles

  server-local:
    build:
      context: .
      dockerfile: ./server/Dockerfile.local
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./server/src:/app/src
