FROM node:20.16.0-slim

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

RUN pwd

RUN ls

RUN npm -v

# for render??
EXPOSE 8081

# Run the built app
CMD ["npm", "run", "start"]