# Use a base image
FROM node:20.16.0-alpine

WORKDIR /app

COPY package*.json ./
COPY ./server ./

# COPY ./shared ../shared
COPY ./ssl ../ssl

RUN npm ci
RUN ls

# Expose the port on which the application will run
EXPOSE 8000

# Define the command to start the application
CMD ["npm", "run", "dev"]