FROM node:20.16.0-slim

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

RUN pwd

RUN ls

RUN npm -v
RUN node -v

# for render??
EXPOSE 8000

RUN test -f /dist/src/server.js && echo "File: /dist/src/server.js exists" || echo "File: /dist/src/server.js does not exist"
RUN test -f dist/src/server.js && echo "File: dist/src/server.js exists" || echo "File: dist/src/server.js does not exist"

# Run the built app
CMD ["node", "dist/src/server.js"]