FROM node:20.16.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Build the TypeScript application
RUN npm run build

# for render??
EXPOSE 8000

# Run the built app
CMD ["node", "dist/src/server.js"]
# CMD ["npm", "run", "start"]