title: Ai Fashion Mirror Docs
description: Documentation for the Ai Fashion Mirror project
theme: just-the-docs

url: https://natapokie.github.io/ai-fashion-mirror/docs/

aux_links:
  Github Repo: https://github.com/natapokie/ai-fashion-mirror